// Copyright 2026 Sun Yimin. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.

//go:build !purego

package mlkem

import (
	"crypto/sha3"

	"github.com/emmansun/gmsm/internal/deps/cpu"
)

var useAVX2 = cpu.X86.HasAVX2

//go:noescape
func internalNTTAVX2(f *ringElement)

//go:noescape
func internalInverseNTTAVX2(f *nttElement)

//go:noescape
func internalNTTMulAccAVX2(acc, lhs, rhs *nttElement)

//go:noescape
func internalNTTMulAccKeyGenAVX2(acc, lhs, rhs *nttElement)

//go:noescape
func decodeAndDecompressU10AVX2(dst []ringElement, c []byte)

//go:noescape
func decodeAndDecompressU11AVX2(dst []ringElement, c []byte)

//go:noescape
func samplePolyCBD2AVX2(f *ringElement, buf *[128]byte)

//go:noescape
func samplePolyCBD3AVX2(f *ringElement, buf *[192]byte)

func nttMulAcc(acc, lhs, rhs *nttElement) {
	if useAVX2 {
		internalNTTMulAccAVX2(acc, lhs, rhs)
		return
	}
	nttMulAccGeneric(acc, lhs, rhs)
}

func internalNTT(f *ringElement) {
	if useAVX2 {
		internalNTTAVX2(f)
		return
	}
	internalNTTGeneric(f)
}

func internalInverseNTT(f *nttElement) {
	if useAVX2 {
		internalInverseNTTAVX2(f)
		return
	}
	internalInverseNTTGeneric(f)
}

func nttMulAccKeyGen(acc, lhs, rhs *nttElement) {
	if useAVX2 {
		internalNTTMulAccKeyGenAVX2(acc, lhs, rhs)
		return
	}
	nttMulAccGeneric(acc, lhs, rhs)
}

func decodeAndDecompressU10(dst []ringElement, c []byte) {
	if useAVX2 {
		decodeAndDecompressU10AVX2(dst, c)
		return
	}
	decodeAndDecompressU10Generic(dst, c)
}

func decodeAndDecompressU11(dst []ringElement, c []byte) {
	if useAVX2 {
		decodeAndDecompressU11AVX2(dst, c)
		return
	}
	decodeAndDecompressU11Generic(dst, c)
}

// samplePolyCBD draws a ringElement from the Dη distribution given a stream of
// random bytes generated by the PRF function, according to FIPS 203, Algorithm 8.
func samplePolyCBD(s []byte, b, η byte) ringElement {
	prf := sha3.NewSHAKE256()
	prf.Write(s)
	prf.Write([]byte{b})
	var B [maxBytesOf64Mulη]byte
	switch {
	case useAVX2 && η == 2:
		prf.Read(B[:128])
		var f ringElement
		samplePolyCBD2AVX2(&f, (*[128]byte)(B[:128]))
		return f
	case useAVX2 && η == 3:
		prf.Read(B[:192])
		var f ringElement
		samplePolyCBD3AVX2(&f, (*[192]byte)(B[:192]))
		return f
	default:
		prf.Read(B[:64*η])
		return samplePolyCBDGeneric(B[:], η)
	}
}
