// Copyright 2026 Sun Yimin. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.

//go:build go1.26 && !purego

package mlkem

import (
	"crypto/sha3"

	"github.com/emmansun/gmsm/internal/deps/cpu"
	"github.com/emmansun/gmsm/internal/keccakx4"
)

var hasRVV = cpu.RISCV64.HasV

var zetasMontgomeryInverse [127]fieldElement

func init() {
	for i := 0; i < 127; i++ {
		zetasMontgomeryInverse[i] = zetasMontgomery[127-i]
	}
}

//go:noescape
func internalNTTMulRVV(out, lhs, rhs *nttElement)

//go:noescape
func internalNTTMulAccRVV(acc, lhs, rhs *nttElement)

//go:noescape
func internalNTTMulAccKeyGenRVV(acc, lhs, rhs *nttElement)

//go:noescape
func internalNTTRVV(f *ringElement)

//go:noescape
func internalInverseNTTRVV(f *nttElement)

//go:noescape
func decodeAndDecompressU10RVV(dst []ringElement, c []byte)

//go:noescape
func decodeAndDecompressU11RVV(dst []ringElement, c []byte)

//go:noescape
func ringCompressAndEncode10RVV(out []byte, f *ringElement)

//go:noescape
func ringCompressAndEncode11RVV(out []byte, f *ringElement)

//go:noescape
func polyAddAssignRVV(dst, src *ringElement)

//go:noescape
func polySubAssignRVV(dst, src *ringElement)

//go:noescape
func samplePolyCBD2RVV(f *ringElement, buf *[128]byte)

//go:noescape
func samplePolyCBD3RVV(f *ringElement, buf *[192]byte)

//go:noescape
func ringCompressAndEncode4RVV(out []byte, f *ringElement)

//go:noescape
func ringDecodeAndDecompress4RVV(b *[encodingSize4]byte, f *ringElement)

//go:noescape
func ringCompressAndEncode5RVV(out []byte, f *ringElement)

//go:noescape
func ringDecodeAndDecompress5RVV(b *[encodingSize5]byte, f *ringElement)

//go:noescape
func ringCompressAndEncode1RVV(out []byte, f *ringElement)

//go:noescape
func rejUniformAsm(buf []byte, a *nttElement, j int) int

func nttMul(acc, lhs, rhs *nttElement) {
	if hasRVV {
		internalNTTMulRVV(acc, lhs, rhs)
		return
	}
	nttMulGeneric(acc, lhs, rhs)
}

func nttMulAcc(acc, lhs, rhs *nttElement) {
	if hasRVV {
		internalNTTMulAccRVV(acc, lhs, rhs)
		return
	}
	nttMulAccGeneric(acc, lhs, rhs)
}

func nttMulAccKeyGen(acc, lhs, rhs *nttElement) {
	if hasRVV {
		internalNTTMulAccKeyGenRVV(acc, lhs, rhs)
		return
	}
	nttMulAccGeneric(acc, lhs, rhs)
}

func internalNTT(f *ringElement) {
	if hasRVV {
		internalNTTRVV(f)
		return
	}
	internalNTTGeneric(f)
}

func internalInverseNTT(f *nttElement) {
	if hasRVV {
		internalInverseNTTRVV(f)
		return
	}
	internalInverseNTTGeneric(f)
}

func decodeAndDecompressU10(dst []ringElement, c []byte) {
	if hasRVV {
		decodeAndDecompressU10RVV(dst, c)
		return
	}
	decodeAndDecompressU10Generic(dst, c)
}

func decodeAndDecompressU11(dst []ringElement, c []byte) {
	if hasRVV {
		decodeAndDecompressU11RVV(dst, c)
		return
	}
	decodeAndDecompressU11Generic(dst, c)
}

// samplePolyCBD draws a ringElement from the Dη distribution given a stream of
// random bytes generated by the PRF function, according to FIPS 203, Algorithm 8.
func samplePolyCBD(s []byte, b, η byte) ringElement {
	prf := sha3.NewSHAKE256()
	prf.Write(s)
	prf.Write([]byte{b})
	var B [maxBytesOf64Mulη]byte
	switch {
	case hasRVV && η == 2:
		prf.Read(B[:128])
		var f ringElement
		samplePolyCBD2RVV(&f, (*[128]byte)(B[:128]))
		return f
	case hasRVV && η == 3:
		prf.Read(B[:192])
		var f ringElement
		samplePolyCBD3RVV(&f, (*[192]byte)(B[:192]))
		return f
	default:
		prf.Read(B[:64*η])
		return samplePolyCBDGeneric(B[:], η)
	}
}

func polyAddAssign(dst *ringElement, src *ringElement) {
	if hasRVV {
		polyAddAssignRVV(dst, src)
		return
	}
	polyAddAssignGeneric(dst, src)
}

func polySubAssign(dst *ringElement, src *ringElement) {
	if hasRVV {
		polySubAssignRVV(dst, src)
		return
	}
	polySubAssignGeneric(dst, src)
}

// ringCompressAndEncode4 appends a 128-byte encoding of a ring element to s,
// compressing two coefficients per byte.
//
// It implements Compress₄, according to FIPS 203, Definition 4.7,
// followed by ByteEncode₄, according to FIPS 203, Algorithm 5.
func ringCompressAndEncode4(s []byte, f *ringElement) []byte {
	s, b := sliceForAppend(s, encodingSize4)
	if hasRVV {
		ringCompressAndEncode4RVV(b, f)
		return s
	}
	ringCompressAndEncode4Generic(b, f)
	return s
}

// ringDecodeAndDecompress4 decodes a 128-byte encoding of a ring element where
// each four bits are mapped to an equidistant distribution.
//
// It implements ByteDecode₄, according to FIPS 203, Algorithm 6,
// followed by Decompress₄, according to FIPS 203, Definition 4.8.
func ringDecodeAndDecompress4(b *[encodingSize4]byte, f *ringElement) {
	if hasRVV {
		ringDecodeAndDecompress4RVV(b, f)
		return
	}
	ringDecodeAndDecompress4Generic(b, f)
}

// ringCompressAndEncode5 appends a 160-byte encoding of a ring element to s,
// compressing eight coefficients per five bytes.
//
// It implements Compress₅, according to FIPS 203, Definition 4.7,
// followed by ByteEncode₅, according to FIPS 203, Algorithm 5.
func ringCompressAndEncode5(s []byte, f *ringElement) []byte {
	if hasRVV {
		s, b := sliceForAppend(s, encodingSize5)
		ringCompressAndEncode5RVV(b, f)
		return s
	}
	return ringCompressAndEncode(s, f, 5)
}

// ringDecodeAndDecompress5 decodes a 160-byte encoding of a ring element where
// each five bits are mapped to an equidistant distribution.
//
// It implements ByteDecode₅, according to FIPS 203, Algorithm 6,
// followed by Decompress₅, according to FIPS 203, Definition 4.8.
func ringDecodeAndDecompress5(bb *[encodingSize5]byte) ringElement {
	if hasRVV {
		var f ringElement
		ringDecodeAndDecompress5RVV(bb, &f)
		return f
	}
	return ringDecodeAndDecompress(bb[:], 5)
}

// ringCompressAndEncode10 appends a 320-byte encoding of a ring element to s,
// compressing four coefficients per five bytes.
//
// It implements Compress₁₀, according to FIPS 203, Definition 4.7,
// followed by ByteEncode₁₀, according to FIPS 203, Algorithm 5.
func ringCompressAndEncode10(s []byte, f *ringElement) []byte {
	s, b := sliceForAppend(s, encodingSize10)
	if hasRVV {
		ringCompressAndEncode10RVV(b, f)
		return s
	}
	ringCompressAndEncode10Generic(b, f)
	return s
}

// ringCompressAndEncode11 appends a 352-byte encoding of a ring element to s,
// compressing eight coefficients per eleven bytes.
//
// It implements Compress₁₁, according to FIPS 203, Definition 4.7,
// followed by ByteEncode₁₁, according to FIPS 203, Algorithm 5.
func ringCompressAndEncode11(s []byte, f *ringElement) []byte {
	if hasRVV {
		s, b := sliceForAppend(s, encodingSize11)
		ringCompressAndEncode11RVV(b, f)
		return s
	}
	return ringCompressAndEncode(s, f, 11)
}

// ringCompressAndEncode1 appends a 32-byte encoding of a ring element to s,
// compressing one coefficients per bit.
//
// It implements Compress₁, according to FIPS 203, Definition 4.7,
// followed by ByteEncode₁, according to FIPS 203, Algorithm 5.
func ringCompressAndEncode1(s []byte, f *ringElement) []byte {
	s, b := sliceForAppend(s, encodingSize1)
	if hasRVV {
		ringCompressAndEncode1RVV(b, f)
		return s
	}
	clear(b)
	ringCompressAndEncode1Generic(b, f)
	return s
}

// sampleNTT draws a uniformly random nttElement from a stream of uniformly
// random bytes generated by the XOF function, according to FIPS 203,
// Algorithm 7.
func sampleNTT(rho []byte, ii, jj byte) nttElement {
	B := sha3.NewSHAKE128()
	B.Write(rho)
	var domain [2]byte
	domain[0] = ii
	domain[1] = jj
	B.Write(domain[:])

	var a nttElement
	var j int // index into a

	// Keep rejUniformAsm on its len==24 fast path, but amortize SHAKE.Read
	// overhead by filling seven 24-byte chunks per squeeze.
	var batch [168]byte

	for j < n {
		B.Read(batch[:])
		for off := 0; off < len(batch) && j < n; off += 24 {
			j += rejUniformAsm(batch[off:off+24], &a, j)
		}
	}
	return a
}

func sampleNTTx4(rho []byte, indices [4][2]byte) [4]nttElement {
	var xof keccakx4.SHAKE128x4
	xof.AbsorbSeed(rho, indices)

	var results [4]nttElement
	var j [4]int
	var batch [4][168]byte

	for {
		xof.Squeeze(batch[0][:], batch[1][:], batch[2][:], batch[3][:])
		allDone := true
		for lane := range 4 {
			if j[lane] >= n {
				continue
			}
			for off := 0; off < 168 && j[lane] < n; off += 24 {
				j[lane] += rejUniformAsm(batch[lane][off:off+24], &results[lane], j[lane])
			}
			if j[lane] < n {
				allDone = false
			}
		}
		if allDone {
			break
		}
	}
	return results
}
