// Copyright 2026 Sun Yimin. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.
// Code generated by generate.go. DO NOT EDIT.

package mlkem

const (
	qInv    = 62209 // q⁻¹ satisfies: q⁻¹ * q = 1 mod 2¹⁶
	qNegInv = 3327  // -q⁻¹ mod 2¹⁶ = 2¹⁶ - q⁻¹
	r       = 2285  // 2¹⁶ % q
	rr      = 1353  // (2¹⁶)² % q
)

var gammasMontgomery = [128]fieldElement{
	2226, 1103, 430, 2899, 555, 2774, 843, 2486,
	2078, 1251, 871, 2458, 1550, 1779, 105, 3224,
	422, 2907, 587, 2742, 177, 3152, 3094, 235,
	3038, 291, 2869, 460, 1574, 1755, 1653, 1676,
	3083, 246, 778, 2551, 1159, 2170, 3182, 147,
	2552, 777, 1483, 1846, 2727, 602, 1119, 2210,
	1739, 1590, 644, 2685, 2457, 872, 349, 2980,
	418, 2911, 329, 3000, 3173, 156, 3254, 75,
	817, 2512, 1097, 2232, 603, 2726, 610, 2719,
	1322, 2007, 2044, 1285, 1864, 1465, 384, 2945,
	2114, 1215, 3193, 136, 1218, 2111, 1994, 1335,
	2455, 874, 220, 3109, 2142, 1187, 1670, 1659,
	2144, 1185, 1799, 1530, 2051, 1278, 794, 2535,
	1819, 1510, 2475, 854, 2459, 870, 478, 2851,
	3221, 108, 3021, 308, 996, 2333, 991, 2338,
	958, 2371, 1869, 1460, 1522, 1807, 1628, 1701,
}

var zetasMontgomery = [128]fieldElement{
	2285, 2571, 2970, 1812, 1493, 1422, 287, 202,
	3158, 622, 1577, 182, 962, 2127, 1855, 1468,
	573, 2004, 264, 383, 2500, 1458, 1727, 3199,
	2648, 1017, 732, 608, 1787, 411, 3124, 1758,
	1223, 652, 2777, 1015, 2036, 1491, 3047, 1785,
	516, 3321, 3009, 2663, 1711, 2167, 126, 1469,
	2476, 3239, 3058, 830, 107, 1908, 3082, 2378,
	2931, 961, 1821, 2604, 448, 2264, 677, 2054,
	2226, 430, 555, 843, 2078, 871, 1550, 105,
	422, 587, 177, 3094, 3038, 2869, 1574, 1653,
	3083, 778, 1159, 3182, 2552, 1483, 2727, 1119,
	1739, 644, 2457, 349, 418, 329, 3173, 3254,
	817, 1097, 603, 610, 1322, 2044, 1864, 384,
	2114, 3193, 1218, 1994, 2455, 220, 2142, 1670,
	2144, 1799, 2051, 794, 1819, 2475, 2459, 478,
	3221, 3021, 996, 991, 958, 1869, 1522, 1628,
}

func fieldMontReduce(a uint32) fieldElement {
	t := uint16(a) * qNegInv
	return fieldReduceOnce(uint16((a + uint32(t)*q) >> 16))
}

func fieldMontMul(a, b fieldElement) fieldElement {
	x := uint32(a) * uint32(b)
	return fieldMontReduce(x)
}

func fieldMontMulSub(a, b, c fieldElement) fieldElement {
	return fieldMontMul(a, fieldSub(b, c))
}

func fieldAddMontMul(a, b, c, d fieldElement) fieldElement {
	return fieldAdd(fieldMontMul(a, b), fieldMontMul(c, d))
}

func nttMontMulAcc(acc, lhs, rhs *nttElement) {
	for i := 0; i < 256; i += 2 {
		a0, a1 := lhs[i], lhs[i+1]
		b0, b1 := rhs[i], rhs[i+1]
		acc[i] = fieldAdd(acc[i], fieldAddMontMul(a0, b0, fieldMontMul(a1, b1), gammasMontgomery[i/2]))
		acc[i+1] = fieldAdd(acc[i+1], fieldAddMontMul(a0, b1, a1, b0))
	}
}

func internalMontNTT(f *ringElement) {
	k := 1
	for len := 128; len >= 2; len /= 2 {
		for start := 0; start < 256; start += 2 * len {
			zeta := zetasMontgomery[k]
			k++
			// Bounds check elimination hint.
			f, flen := f[start:start+len], f[start+len:start+len+len]
			for j := 0; j < len; j++ {
				t := fieldMontMul(zeta, flen[j])
				flen[j] = fieldSub(f[j], t)
				f[j] = fieldAdd(f[j], t)
			}
		}
	}
}

func internalMontInverseNTT(f *nttElement) {
	k := 127
	for len := 2; len <= 128; len *= 2 {
		for start := 0; start < 256; start += 2 * len {
			zeta := zetasMontgomery[k]
			k--
			// Bounds check elimination hint.
			f, flen := f[start:start+len], f[start+len:start+len+len]
			for j := 0; j < len; j++ {
				t := f[j]
				f[j] = fieldAdd(t, flen[j])
				flen[j] = fieldMontMulSub(zeta, flen[j], t)
			}
		}
	}
	for i := range f {
		f[i] = fieldMontMul(f[i], 1441) // 1441 = 128⁻¹ mod q * r^2 mod q
	}
}
