// Copyright 2026 Sun Yimin. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.

//go:build !purego

package mlkem

import "crypto/sha3"

// NEON is mandatory on all ARMv8-A (arm64) cores; no runtime detection needed.

// nttZetasL5L6Packed stores prepacked zetas for forward NTT tail layers.
// Layout:
//
//	[0..15]  -> L5 vectors: [z0 x4, z1 x4]
//	[16..31] -> L6 vectors: [z0,z0,z1,z1,z2,z2,z3,z3]
var nttZetasL5L6Packed = [32][8]fieldElement{
	{1223, 1223, 1223, 1223, 652, 652, 652, 652},
	{2777, 2777, 2777, 2777, 1015, 1015, 1015, 1015},
	{2036, 2036, 2036, 2036, 1491, 1491, 1491, 1491},
	{3047, 3047, 3047, 3047, 1785, 1785, 1785, 1785},
	{516, 516, 516, 516, 3321, 3321, 3321, 3321},
	{3009, 3009, 3009, 3009, 2663, 2663, 2663, 2663},
	{1711, 1711, 1711, 1711, 2167, 2167, 2167, 2167},
	{126, 126, 126, 126, 1469, 1469, 1469, 1469},
	{2476, 2476, 2476, 2476, 3239, 3239, 3239, 3239},
	{3058, 3058, 3058, 3058, 830, 830, 830, 830},
	{107, 107, 107, 107, 1908, 1908, 1908, 1908},
	{3082, 3082, 3082, 3082, 2378, 2378, 2378, 2378},
	{2931, 2931, 2931, 2931, 961, 961, 961, 961},
	{1821, 1821, 1821, 1821, 2604, 2604, 2604, 2604},
	{448, 448, 448, 448, 2264, 2264, 2264, 2264},
	{677, 677, 677, 677, 2054, 2054, 2054, 2054},

	{2226, 2226, 430, 430, 555, 555, 843, 843},
	{2078, 2078, 871, 871, 1550, 1550, 105, 105},
	{422, 422, 587, 587, 177, 177, 3094, 3094},
	{3038, 3038, 2869, 2869, 1574, 1574, 1653, 1653},
	{3083, 3083, 778, 778, 1159, 1159, 3182, 3182},
	{2552, 2552, 1483, 1483, 2727, 2727, 1119, 1119},
	{1739, 1739, 644, 644, 2457, 2457, 349, 349},
	{418, 418, 329, 329, 3173, 3173, 3254, 3254},
	{817, 817, 1097, 1097, 603, 603, 610, 610},
	{1322, 1322, 2044, 2044, 1864, 1864, 384, 384},
	{2114, 2114, 3193, 3193, 1218, 1218, 1994, 1994},
	{2455, 2455, 220, 220, 2142, 2142, 1670, 1670},
	{2144, 2144, 1799, 1799, 2051, 2051, 794, 794},
	{1819, 1819, 2475, 2475, 2459, 2459, 478, 478},
	{3221, 3221, 3021, 3021, 996, 996, 991, 991},
	{958, 958, 1869, 1869, 1522, 1522, 1628, 1628},
}

//go:noescape
func internalNTTNEON(f *ringElement)

//go:noescape
func internalInverseNTTNEON(f *nttElement)

//go:noescape
func internalNTTMulAccNEON(acc, lhs, rhs *nttElement)

//go:noescape
func internalNTTMulAccKeyGenNEON(acc, lhs, rhs *nttElement)

//go:noescape
func samplePolyCBD2NEON(dst *ringElement, buf *[128]byte)

//go:noescape
func samplePolyCBD3NEON(dst *ringElement, buf *[192]byte)

//go:noescape
func decodeAndDecompressU10NEON(dst []ringElement, c []byte)

//go:noescape
func decodeAndDecompressU11NEON(dst []ringElement, c []byte)

func nttMulAcc(acc, lhs, rhs *nttElement) {
	internalNTTMulAccNEON(acc, lhs, rhs)
}

func internalNTT(f *ringElement) {
	internalNTTNEON(f)
}

func internalInverseNTT(f *nttElement) {
	internalInverseNTTNEON(f)
}

func nttMulAccKeyGen(acc, lhs, rhs *nttElement) {
	internalNTTMulAccKeyGenNEON(acc, lhs, rhs)
}

func decodeAndDecompressU10(dst []ringElement, c []byte) {
	decodeAndDecompressU10NEON(dst, c)
}

func decodeAndDecompressU11(dst []ringElement, c []byte) {
	decodeAndDecompressU11NEON(dst, c)
}

// samplePolyCBD draws a ringElement from the Dη distribution given a stream of
// random bytes generated by the PRF function, according to FIPS 203, Algorithm 8.
func samplePolyCBD(s []byte, b, η byte) ringElement {
	prf := sha3.NewSHAKE256()
	prf.Write(s)
	prf.Write([]byte{b})
	var B [maxBytesOf64Mulη]byte
	switch η {
	case 2:
		prf.Read(B[:128])
		var f ringElement
		samplePolyCBD2NEON(&f, (*[128]byte)(B[:128]))
		return f
	case 3:
		prf.Read(B[:192])
		var f ringElement
		samplePolyCBD3NEON(&f, (*[192]byte)(B[:192]))
		return f
	default:
		prf.Read(B[:64*η])
		return samplePolyCBDGeneric(B[:], η)
	}
}
