// Copyright 2026 Sun Yimin. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.
// Code generated by generate.go. DO NOT EDIT.

package mlkem

import (
	"math/big"
	"testing"
)

func TestConstants(t *testing.T) {
	q1 := big.NewInt(q)
	a := big.NewInt(1 << 16)

	r1 := new(big.Int)
	r1.Mod(a, q1)
	if r1.Cmp(big.NewInt(int64(r))) != 0 {
		t.Fatalf("r = 2^16 mod q = %d, expected %d", r1, r)
	}

	q1Inv := new(big.Int)
	q1Inv.ModInverse(q1, a)
	tmp := new(big.Int)
	tmp.Mul(q1Inv, q1)
	tmp.Mod(tmp, a)
	if tmp.Cmp(big.NewInt(1)) != 0 {
		t.Fatalf("q^-1 mod 2^16 = %d, expected %d", q1Inv, qInv)
	}
	if q1Inv.Cmp(big.NewInt(int64(qInv))) != 0 {
		t.Fatalf("q^-1 mod 2^16 = %d, expected %d", q1Inv, qInv)
	}

	q1Neg := new(big.Int)
	q1Neg.Sub(a, q1)
	q1NegInv := new(big.Int)
	q1NegInv.ModInverse(q1Neg, a)
	if q1NegInv.Cmp(big.NewInt(int64(qNegInv))) != 0 {
		t.Fatalf("-q^-1 mod 2^16 = %d, expected %d", q1NegInv, qNegInv)
	}

	dgreeInv := new(big.Int)
	dgreeInv.ModInverse(big.NewInt(int64(128)), q1)
	dgreeInv.Mul(dgreeInv, r1)
	dgreeInv.Mul(dgreeInv, r1)
	dgreeInv.Mod(dgreeInv, q1)
	if dgreeInv.Int64() != 1441 {
		t.Fatalf("dgreeInv = ((128^(-1) mod q) * r^2) mod q  = %d, expected 1441", dgreeInv)
	}

	// test gammasMontgomery
	for i, g := range gammas {
		gMont := big.NewInt(int64(g))
		gMont.Mul(gMont, r1)
		gMont.Mod(gMont, q1)
		if gMont.Cmp(big.NewInt(int64(gammasMontgomery[i]))) != 0 {
			t.Fatalf("gammasMontgomery[%d] = %d, expected %d", i, gMont, gammasMontgomery[i])
		}
	}

	// test zetasMontgomery
	for i, z := range zetas {
		zMont := big.NewInt(int64(z))
		zMont.Mul(zMont, r1)
		zMont.Mod(zMont, q1)
		if zMont.Cmp(big.NewInt(int64(zetasMontgomery[i]))) != 0 {
			t.Fatalf("zetasMontgomery[%d] = %d, expected %d", i, zMont, zetasMontgomery[i])
		}
	}
}

func TestFieldMontMul(t *testing.T) {
	const rInv = 169 // 2^16 * rInv = 1 mod q
	for a := fieldElement(q - 1000); a < q; a++ {
		for b := fieldElement(q - 1000); b < q; b++ {
			got := fieldMontMul(a, b)
			// Montgomery reduction computes a*b*R^{-1} mod q where R = 2^16.
			exp := fieldElement((uint32(a) * uint32(b) * uint32(rInv)) % q)
			if got != exp {
				t.Fatalf("%d * %d = %d, expected %d", a, b, got, exp)
			}

			got = fieldMontMul(a, fieldElement((uint32(b)*uint32(r))%q))
			exp = fieldElement((uint32(a) * uint32(b)) % q)
			if got != exp {
				t.Fatalf("%d * %d = %d, expected %d", a, b, got, exp)
			}
		}
	}
}

func TestNTTMulAcc(t *testing.T) {
	lhs := nttElement(randomRingElement())
	rhs := nttElement(randomRingElement())
	var acc, accMont nttElement
	nttMulAccGeneric(&acc, &lhs, &rhs)
	nttMontMulAcc(&accMont, &lhs, &rhs)

	for i := range acc {
		exp := fieldMontReduce(uint32(acc[i]))
		if accMont[i] != exp {
			t.Fatalf("nttMulAcc: expected %d, got %d", exp, accMont[i])
		}
	}
}

func TestNTT(t *testing.T) {
	r := randomRingElement()
	r1 := r

	internalNTTGeneric(&r)
	internalMontNTT(&r1)

	for i, v := range r {
		if v != r1[i] {
			t.Errorf("expected %v, got %v", v, r1[i])
		}
	}
}

func TestInverseNTT(t *testing.T) {
	r := randomRingElement()
	r1 := r

	internalNTTGeneric(&r)
	internalMontNTT(&r1)

	for i, v := range r {
		if v != r1[i] {
			t.Errorf("expected %v, got %v", v, r1[i])
		}
	}

	r2 := nttElement(r)
	r3 := nttElement(r1)

	internalInverseNTTGeneric(&r2)
	internalMontInverseNTT(&r3)
	for i, v := range r2 {
		if v != fieldMontReduce(uint32(r3[i])) {
			t.Errorf("expected %v, got %v", v, r2[i])
		}
	}
}
