// Copyright 2026 Sun Yimin. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.

//go:build !purego

package mlkem

import "crypto/sha3"

// NEON is mandatory on all ARMv8-A (arm64) cores; no runtime detection needed.

//go:noescape
func internalNTTNEON(f *ringElement)

//go:noescape
func internalInverseNTTNEON(f *nttElement)

//go:noescape
func internalNTTMulAccNEON(acc, lhs, rhs *nttElement)

//go:noescape
func internalNTTMulAccKeyGenNEON(acc, lhs, rhs *nttElement)

//go:noescape
func samplePolyCBD2NEON(dst *ringElement, buf *[128]byte)

func nttMulAcc(acc, lhs, rhs *nttElement) {
	internalNTTMulAccNEON(acc, lhs, rhs)
}

func internalNTT(f *ringElement) {
	internalNTTNEON(f)
}

func internalInverseNTT(f *nttElement) {
	internalInverseNTTNEON(f)
}

func nttMulAccKeyGen(acc, lhs, rhs *nttElement) {
	internalNTTMulAccKeyGenNEON(acc, lhs, rhs)
}

func decodeAndDecompressU10(dst []ringElement, c []byte) {
	decodeAndDecompressU10Generic(dst, c)
}

func decodeAndDecompressU11(dst []ringElement, c []byte) {
	decodeAndDecompressU11Generic(dst, c)
}

// samplePolyCBD draws a ringElement from the Dη distribution given a stream of
// random bytes generated by the PRF function, according to FIPS 203, Algorithm 8.
func samplePolyCBD(s []byte, b, η byte) ringElement {
	prf := sha3.NewSHAKE256()
	prf.Write(s)
	prf.Write([]byte{b})
	var B [maxBytesOf64Mulη]byte
	switch η {
	case 2:
		prf.Read(B[:128])
		var f ringElement
		samplePolyCBD2NEON(&f, (*[128]byte)(B[:128]))
		return f
	case 3:
		prf.Read(B[:192])
		return samplePolyCBD3Arm64((*[192]byte)(B[:192]))
	default:
		prf.Read(B[:64*η])
		return samplePolyCBDGeneric(B[:], η)
	}
}

// samplePolyCBD3Arm64 computes Dη=3 coefficients from 192 PRF bytes.
// Kept separate for future replacement by a NEON implementation.
func samplePolyCBD3Arm64(B *[192]byte) ringElement {
	var f ringElement
	for i := 0; i < n; i += 4 {
		j := (i >> 2) * 3
		bits := uint32(B[j]) | uint32(B[j+1])<<8 | uint32(B[j+2])<<16

		for k := range 4 {
			off := 6 * k
			sum := ((bits >> off) & 1) + ((bits >> (off + 1)) & 1) + ((bits >> (off + 2)) & 1)
			sub := ((bits >> (off + 3)) & 1) + ((bits >> (off + 4)) & 1) + ((bits >> (off + 5)) & 1)
			f[i+k] = fieldSub(fieldElement(sum), fieldElement(sub))
		}
	}
	return f
}
