// Copyright 2026 Sun Yimin. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.
// Code generated by generate.go. DO NOT EDIT.

//go:build riscv64 && go1.26 && !purego

package mlkem

import (
	mathrand "math/rand/v2"
	"testing"
)

func TestNTTMul(t *testing.T) {
	if !hasRVV {
		t.Skip("skipping test: RVV not available")
	}
	for range 64 {
		var lhs, rhs, got, want nttElement
		for i := range lhs {
			lhs[i] = fieldElement(mathrand.IntN(q))
			rhs[i] = fieldElement(mathrand.IntN(q))
		}

		internalNTTMulRVV(&got, &lhs, &rhs)
		nttMontMul(&want, &lhs, &rhs)

		for i := range got {
			if got[i] != want[i] {
				t.Fatalf("index %d: got %d, want %d", i, got[i], want[i])
			}
		}
	}
}

func TestNTTMulAccRVV(t *testing.T) {
	if !hasRVV {
		t.Skip("skipping test: RVV not available")
	}
	for range 64 {
		var acc, lhs, rhs, got, want nttElement
		for i := range lhs {
			lhs[i] = fieldElement(mathrand.IntN(q))
			rhs[i] = fieldElement(mathrand.IntN(q))
			acc[i] = fieldElement(mathrand.Intn(q))
		}

		copy(got[:], acc[:])
		copy(want[:], acc[:])
		internalNTTMulAccRVV(&got, &lhs, &rhs)
		nttMontMulAcc(&want, &lhs, &rhs)

		for i := range got {
			if got[i] != want[i] {
				t.Fatalf("index %d: got %d, want %d", i, got[i], want[i])
			}
		}
	}
}
