// Copyright 2026 Sun Yimin. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.
// Code generated by generate.go. DO NOT EDIT.

//go:build riscv64 && go1.27 && !purego

package sm4

//go:noescape
func gcmSm4Init(productTable *[256]byte, rk []uint32, inst int)

//go:noescape
func gcmSm4Data(productTable *[256]byte, data []byte, T *[16]byte)
