// Copyright 2026 Sun Yimin. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.
// Code generated by generate.go. DO NOT EDIT.

//go:build riscv64 && go1.27 && !purego

package sm4

import (
	"bytes"
	"encoding/hex"
	"os"
	"strconv"
	"testing"

	"github.com/emmansun/gmsm/internal/deps/cpu"
)

func generateProductTableZvkg(t *testing.T, key []byte, table *[256]byte) {
	t.Helper()
	c, err := newCipherGeneric(key[:])
	if err != nil {
		t.Fatal(err)
	}
	c1 := c.(*sm4Cipher)

	gcmSm4Init(table, c1.enc[:], INST_SM4)
}

func TestGcmSm4InitZvkg(t *testing.T) {
	if !hasGHASH {
		t.Skip("skipping test on unsupported CPU")
	}
	var table [256]byte
	key := [16]byte{0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef, 0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54, 0x32, 0x10}
	generateProductTableZvkg(t, key[:], &table)
	c, err := NewCipher(key[:])
	if err != nil {
		t.Fatal(err)
	}
	dst := make([]byte, 16)
	c.Encrypt(dst, dst)
	if !bytes.Equal(dst, table[:16]) {
		t.Errorf("unexpected result: got %x, want %x", dst, table[:16])
	}
}

func TestGcmSm4DataZvkg(t *testing.T) {
	if !hasGHASH {
		t.Skip("skipping test on unsupported CPU")
	}
	var table [256]byte
	var y [16]byte
	for i, c := range cases {
		clear(table[:])
		key := c.key
		generateProductTableZvkg(t, key[:], &table)
		data := c.data
		expected, _ := hex.DecodeString(c.dataTag)
		reversed := make([]byte, len(expected))
		for i := range expected {
			reversed[i] = expected[len(expected)-1-i]
		}
		clear(y[:])
		gcmSm4Data(&table, data, &y)
		if !bytes.Equal(y[:], reversed) {
			t.Errorf("case %d: unexpected result: got %x, want %x", i, y, reversed)
		}
	}
}

func TestGcmSm4FinishZvkg(t *testing.T) {
	if !hasGHASH {
		t.Skip("skipping test on unsupported CPU")
	}
	var table [256]byte
	var y [16]byte
	var tMask [16]byte

	for i, c := range cases {
		clear(table[:])
		key := c.key
		generateProductTableZvkg(t, key[:], &table)
		data := c.data
		expected, _ := hex.DecodeString(c.expected)
		clear(y[:])
		gcmSm4Data(&table, data, &y)
		gcmSm4Finish(&table, &tMask, &y, 0, uint64(len(data)))
		if !bytes.Equal(y[:], expected) {
			t.Errorf("case %d: unexpected result: got %x, want %x", i, y, expected)
		}
	}
}

func TestRVVConfiguredVLEN(t *testing.T) {
	if !cpu.RISCV64.HasV {
		t.Skip("RVV not available")
	}

	expectedText := os.Getenv("EXPECTED_VLEN")
	if expectedText == "" {
		t.Skip("EXPECTED_VLEN is not set")
	}

	expected, err := strconv.ParseUint(expectedText, 10, 64)
	if err != nil {
		t.Fatalf("invalid EXPECTED_VLEN %q: %v", expectedText, err)
	}

	if cpu.RISCV64.VLENB == 0 {
		t.Fatal("RVV is present but VLENB was not initialized")
	}

	got := uint64(cpu.RISCV64.VLENB) * 8
	if got != expected {
		t.Fatalf(
			"VLEN mismatch: got=%d bits want=%d bits, VLENB=%d",
			got,
			expected,
			cpu.RISCV64.VLENB,
		)
	}

	t.Logf(
		"confirmed QEMU VLEN=%d bits, VLENB=%d bytes",
		got,
		cpu.RISCV64.VLENB,
	)
}
