// Copyright 2026 Sun Yimin. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.
// Code generated by generate.go. DO NOT EDIT.

//go:build riscv64 && go1.27 && !purego

package sm4

import (
	"fmt"
	"testing"
)

func generateProductTable(t *testing.T, key []byte, table *[256]byte) {
	t.Helper()
	c, err := newCipherGeneric(key[:])
	if err != nil {
		t.Fatal(err)
	}
	c1 := c.(*sm4Cipher)

	gcmSm4Init(table, c1.enc[:], INST_SM4)
}

func TestGcmSm4Init(t *testing.T) {
	if !hasGHASH {
		t.Skip("skipping test on unsupported CPU")
	}
	var table [256]byte
	key := [16]byte{0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef, 0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54, 0x32, 0x10}
	generateProductTable(t, key[:], &table)
	c, err := NewCipher(key[:])
	if err != nil {
		t.Fatal(err)
	}
	dst := make([]byte, 16)
	c.Encrypt(dst, dst)
	fmt.Printf("%x, H=%x\n", dst, table[:16])

}
