// Copyright 2026 Sun Yimin. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.
// Code generated by generate.go. DO NOT EDIT.

//go:build !purego

#include "textflag.h"

#include "sm4ni_macros_amd64.s"

#define XK AX
#define DST CX
#define SRC BX
#define IV_LOW_LE DX
#define IV_HIGH_LE SI

// func ctrBlocks1Asm(xk *uint32, dst, src *[BlockSize]byte, ivlo, ivhi uint64)
TEXT ·ctrBlocks1Asm(SB), NOSPLIT, $0
	MOVQ xk+0(FP), XK
	MOVQ dst+8(FP), DST
	MOVQ src+16(FP), SRC
	MOVQ ivlo+24(FP), IV_LOW_LE
	MOVQ ivhi+32(FP), IV_HIGH_LE

	VMOVQ IV_LOW_LE, X0
	VPINSRQ $1, IV_HIGH_LE, X0, X0
	VPSHUFB ·flip_mask(SB), X0, X0
	VSM4RNDS32_MEM_NO_OFF_RAX(0)
	VPSHUFB ·bswap_mask(SB), X0, X0

	VPXOR (SRC), X0, X0
	VMOVDQU X0, (DST)

	RET

// func ctrBlocks2Asm(xk *uint32, dst, src *[2 * BlockSize]byte, ivlo, ivhi uint64)
TEXT ·ctrBlocks2Asm(SB), NOSPLIT, $0
	MOVQ xk+0(FP), XK
	MOVQ dst+8(FP), DST
	MOVQ src+16(FP), SRC
	MOVQ ivlo+24(FP), IV_LOW_LE
	MOVQ ivhi+32(FP), IV_HIGH_LE

	VMOVQ IV_LOW_LE, X0
	VPINSRQ $1, IV_HIGH_LE, X0, X0

	ADDQ $1, IV_LOW_LE
	ADCQ $0, IV_HIGH_LE
	VMOVQ IV_LOW_LE, X1
	VPINSRQ $1, IV_HIGH_LE, X1, X1

	VPSHUFB ·flip_mask(SB), X0, X0
	VPSHUFB ·flip_mask(SB), X1, X1
	VSM4RNDS32_MEM_NO_OFF_RAX(0)
	VSM4RNDS32_MEM_NO_OFF_RAX(1)
	VPSHUFB ·bswap_mask(SB), X0, X0
	VPSHUFB ·bswap_mask(SB), X1, X1

	VPXOR (SRC), X0, X0
	VPXOR 16(SRC), X1, X1
	VMOVDQU X0, (DST)
	VMOVDQU X1, 16(DST)

	RET

// func ctrBlocks4Asm(xk *uint32, dst, src *[4 * BlockSize]byte, ivlo, ivhi uint64)
TEXT ·ctrBlocks4Asm(SB), NOSPLIT, $0
	MOVQ xk+0(FP), XK
	MOVQ dst+8(FP), DST
	MOVQ src+16(FP), SRC
	MOVQ ivlo+24(FP), IV_LOW_LE
	MOVQ ivhi+32(FP), IV_HIGH_LE

	VMOVQ IV_LOW_LE, X0
	VPINSRQ $1, IV_HIGH_LE, X0, X0

	ADDQ $1, IV_LOW_LE
	ADCQ $0, IV_HIGH_LE
	VMOVQ IV_LOW_LE, X1
	VPINSRQ $1, IV_HIGH_LE, X1, X1

	ADDQ $1, IV_LOW_LE
	ADCQ $0, IV_HIGH_LE
	VMOVQ IV_LOW_LE, X2
	VPINSRQ $1, IV_HIGH_LE, X2, X2

	ADDQ $1, IV_LOW_LE
	ADCQ $0, IV_HIGH_LE
	VMOVQ IV_LOW_LE, X3
	VPINSRQ $1, IV_HIGH_LE, X3, X3

	VPSHUFB ·flip_mask(SB), X0, X0
	VPSHUFB ·flip_mask(SB), X1, X1
	VPSHUFB ·flip_mask(SB), X2, X2
	VPSHUFB ·flip_mask(SB), X3, X3
	VSM4RNDS32_MEM_NO_OFF_RAX(0)
	VSM4RNDS32_MEM_NO_OFF_RAX(1)
	VSM4RNDS32_MEM_NO_OFF_RAX(2)
	VSM4RNDS32_MEM_NO_OFF_RAX(3)
	VPSHUFB ·bswap_mask(SB), X0, X0
	VPSHUFB ·bswap_mask(SB), X1, X1
	VPSHUFB ·bswap_mask(SB), X2, X2
	VPSHUFB ·bswap_mask(SB), X3, X3

	VPXOR (SRC), X0, X0
	VPXOR 16(SRC), X1, X1
	VPXOR 32(SRC), X2, X2
	VPXOR 48(SRC), X3, X3
	VMOVDQU X0, (DST)
	VMOVDQU X1, 16(DST)
	VMOVDQU X2, 32(DST)
	VMOVDQU X3, 48(DST)
	RET

// func ctrBlocks8Asm(xk *uint32, dst, src *[8 * BlockSize]byte, ivlo, ivhi uint64)
TEXT ·ctrBlocks8Asm(SB), NOSPLIT, $0
	MOVQ xk+0(FP), XK
	MOVQ dst+8(FP), DST
	MOVQ src+16(FP), SRC
	MOVQ ivlo+24(FP), IV_LOW_LE
	MOVQ ivhi+32(FP), IV_HIGH_LE

	VMOVQ IV_LOW_LE, X0
	VPINSRQ $1, IV_HIGH_LE, X0, X0

	ADDQ $1, IV_LOW_LE
	ADCQ $0, IV_HIGH_LE
	VMOVQ IV_LOW_LE, X1
	VPINSRQ $1, IV_HIGH_LE, X1, X1

	ADDQ $1, IV_LOW_LE
	ADCQ $0, IV_HIGH_LE
	VMOVQ IV_LOW_LE, X2
	VPINSRQ $1, IV_HIGH_LE, X2, X2

	ADDQ $1, IV_LOW_LE
	ADCQ $0, IV_HIGH_LE
	VMOVQ IV_LOW_LE, X3
	VPINSRQ $1, IV_HIGH_LE, X3, X3

	ADDQ $1, IV_LOW_LE
	ADCQ $0, IV_HIGH_LE
	VMOVQ IV_LOW_LE, X4
	VPINSRQ $1, IV_HIGH_LE, X4, X4

	ADDQ $1, IV_LOW_LE
	ADCQ $0, IV_HIGH_LE
	VMOVQ IV_LOW_LE, X5
	VPINSRQ $1, IV_HIGH_LE, X5, X5

	ADDQ $1, IV_LOW_LE
	ADCQ $0, IV_HIGH_LE
	VMOVQ IV_LOW_LE, X6
	VPINSRQ $1, IV_HIGH_LE, X6, X6

	ADDQ $1, IV_LOW_LE
	ADCQ $0, IV_HIGH_LE
	VMOVQ IV_LOW_LE, X7
	VPINSRQ $1, IV_HIGH_LE, X7, X7

	VPSHUFB ·flip_mask(SB), X0, X0
	VPSHUFB ·flip_mask(SB), X1, X1
	VPSHUFB ·flip_mask(SB), X2, X2
	VPSHUFB ·flip_mask(SB), X3, X3
	VPSHUFB ·flip_mask(SB), X4, X4
	VPSHUFB ·flip_mask(SB), X5, X5
	VPSHUFB ·flip_mask(SB), X6, X6
	VPSHUFB ·flip_mask(SB), X7, X7
	VSM4RNDS32_MEM_NO_OFF_RAX(0)
	VSM4RNDS32_MEM_NO_OFF_RAX(1)
	VSM4RNDS32_MEM_NO_OFF_RAX(2)
	VSM4RNDS32_MEM_NO_OFF_RAX(3)
	VSM4RNDS32_MEM_NO_OFF_RAX(4)
	VSM4RNDS32_MEM_NO_OFF_RAX(5)
	VSM4RNDS32_MEM_NO_OFF_RAX(6)
	VSM4RNDS32_MEM_NO_OFF_RAX(7)
	VPSHUFB ·bswap_mask(SB), X0, X0
	VPSHUFB ·bswap_mask(SB), X1, X1
	VPSHUFB ·bswap_mask(SB), X2, X2
	VPSHUFB ·bswap_mask(SB), X3, X3
	VPSHUFB ·bswap_mask(SB), X4, X4
	VPSHUFB ·bswap_mask(SB), X5, X5
	VPSHUFB ·bswap_mask(SB), X6, X6
	VPSHUFB ·bswap_mask(SB), X7, X7

	VPXOR (SRC), X0, X0
	VPXOR 16(SRC), X1, X1
	VPXOR 32(SRC), X2, X2
	VPXOR 48(SRC), X3, X3
	VPXOR 64(SRC), X4, X4
	VPXOR 80(SRC), X5, X5
	VPXOR 96(SRC), X6, X6
	VPXOR 112(SRC), X7, X7
	VMOVDQU X0, (DST)
	VMOVDQU X1, 16(DST)
	VMOVDQU X2, 32(DST)
	VMOVDQU X3, 48(DST)
	VMOVDQU X4, 64(DST)
	VMOVDQU X5, 80(DST)
	VMOVDQU X6, 96(DST)
	VMOVDQU X7, 112(DST)
	RET
