// Copyright 2026 Sun Yimin. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.
// Code generated by generate.go. DO NOT EDIT.

//go:build !purego

#include "textflag.h"

#include "sm4ni_macros_amd64.s"
#include "xts_macros_amd64.s"

#define B0 X0
#define B1 X1
#define B2 X2
#define B3 X3
#define B4 X4
#define B5 X5
#define B6 X6
#define B7 X7

#define TW X10

#define T0 X11
#define T1 X12
#define T2 X13
#define POLY X14
#define BSWAP X15

// func encryptSm4NiXts(xk *uint32, tweak *[BlockSize]byte, dst, src []byte, isGB bool)
TEXT ·encryptSm4NiXts(SB),0,$256-65
	MOVQ xk+0(FP), AX
	MOVQ tweak+8(FP), BX
	MOVQ dst+16(FP), CX
	MOVQ src+40(FP), DX
	MOVQ src_len+48(FP), DI
	MOVBQZX isGB+64(FP), R12

	TESTQ R12, R12
	JNE avx2_gb_init
	VMOVDQU gcmPoly<>(SB), POLY
	JMP avx2_init_done
avx2_gb_init:
	VMOVDQU gbGcmPoly<>(SB), POLY
	VMOVDQU ·bswap_mask(SB), BSWAP
avx2_init_done:	
	VMOVDQU (0*16)(BX), TW

avxXtsSm4EncOctets:
	CMPQ DI, $128
	JB avxXtsSm4EncNibbles
	SUBQ $128, DI

	TESTQ R12, R12
	JNE avx2_gb_8tweaks
	// prepare tweaks
	avxPrepare8Tweaks
	JMP avx2_8blocks_done
avx2_gb_8tweaks:
	avxPrepareGB8Tweaks
avx2_8blocks_done:
	// load 8 blocks for encryption
	avxLoad8Blocks

	VPSHUFB ·flip_mask(SB), B0, B0
	VPSHUFB ·flip_mask(SB), B1, B1
	VPSHUFB ·flip_mask(SB), B2, B2
	VPSHUFB ·flip_mask(SB), B3, B3
	VPSHUFB ·flip_mask(SB), B4, B4
	VPSHUFB ·flip_mask(SB), B5, B5
	VPSHUFB ·flip_mask(SB), B6, B6
	VPSHUFB ·flip_mask(SB), B7, B7
	VSM4RNDS32_MEM_RAX(0)
	VSM4RNDS32_MEM_RAX(1)
	VSM4RNDS32_MEM_RAX(2)
	VSM4RNDS32_MEM_RAX(3)
	VSM4RNDS32_MEM_RAX(4)
	VSM4RNDS32_MEM_RAX(5)
	VSM4RNDS32_MEM_RAX(6)
	VSM4RNDS32_MEM_RAX(7)
	VPSHUFB ·bswap_mask(SB), B0, B0
	VPSHUFB ·bswap_mask(SB), B1, B1
	VPSHUFB ·bswap_mask(SB), B2, B2
	VPSHUFB ·bswap_mask(SB), B3, B3
	VPSHUFB ·bswap_mask(SB), B4, B4
	VPSHUFB ·bswap_mask(SB), B5, B5
	VPSHUFB ·bswap_mask(SB), B6, B6
	VPSHUFB ·bswap_mask(SB), B7, B7

	avxStore8Blocks

	LEAQ 128(DX), DX
	LEAQ 128(CX), CX

	JMP avxXtsSm4EncOctets

avxXtsSm4EncNibbles:
	CMPQ DI, $64
	JB avxXtsSm4EncSingles
	SUBQ $64, DI

	TESTQ R12, R12
	JNE avx2_gb_4tweaks
	// prepare tweaks
	avxPrepare4Tweaks
	JMP avx2_4tweaks_done
avx2_gb_4tweaks:
	avxPrepareGB4Tweaks
avx2_4tweaks_done:
	// load 4 blocks for encryption
	avxLoad4Blocks

	VPSHUFB ·flip_mask(SB), B0, B0
	VPSHUFB ·flip_mask(SB), B1, B1
	VPSHUFB ·flip_mask(SB), B2, B2
	VPSHUFB ·flip_mask(SB), B3, B3
	VSM4RNDS32_MEM_RAX(0)
	VSM4RNDS32_MEM_RAX(1)
	VSM4RNDS32_MEM_RAX(2)
	VSM4RNDS32_MEM_RAX(3)
	VPSHUFB ·bswap_mask(SB), B0, B0
	VPSHUFB ·bswap_mask(SB), B1, B1
	VPSHUFB ·bswap_mask(SB), B2, B2
	VPSHUFB ·bswap_mask(SB), B3, B3

	avxStore4Blocks

	LEAQ 64(DX), DX
	LEAQ 64(CX), CX

avxXtsSm4EncSingles:
	CMPQ DI, $16
	JB avxXtsSm4EncTail
	SUBQ $16, DI

	// load 1 block for encryption
	VMOVDQU (16*0)(DX), B0
	
	VPXOR TW, B0, B0
	VPSHUFB ·flip_mask(SB), B0, B0
	VSM4RNDS32_MEM_RAX(0)
	VPSHUFB ·bswap_mask(SB), B0, B0
	VPXOR TW, B0, B0
	VMOVDQU B0, (16*0)(CX)
	TESTQ R12, R12
	JNE avx2_gb_sigle_mul2
	avxMul2Inline
	JMP avx2_sigle_mul2_done
avx2_gb_sigle_mul2:
	avxMul2GBInline
avx2_sigle_mul2_done:
	LEAQ 16(DX), DX
	LEAQ 16(CX), CX

	JMP avxXtsSm4EncSingles

avxXtsSm4EncTail:
	TESTQ DI, DI
	JE avxXtsSm4EncDone

	LEAQ -16(CX), R8
	VMOVDQU (16*0)(R8), B0
	VMOVDQU B0, (16*0)(SP)

	CMPQ DI, $8
	JB   avx_loop_1b
	SUBQ  $8, DI
	MOVQ (DX)(DI*1), R9
	MOVQ (SP)(DI*1), R10
	MOVQ R9, (SP)(DI*1)
	MOVQ R10, (CX)(DI*1)

	TESTQ DI, DI
	JE avxXtsSm4EncTailEnc

avx_loop_1b:
	SUBQ  $1, DI
	MOVB (DX)(DI*1), R9
	MOVB (SP)(DI*1), R10
	MOVB R9, (SP)(DI*1)
	MOVB R10, (CX)(DI*1)
	TESTQ DI, DI
	JNE   avx_loop_1b

avxXtsSm4EncTailEnc:
	VMOVDQU (16*0)(SP), B0
	VPXOR TW, B0, B0
	VPSHUFB ·flip_mask(SB), B0, B0
	VSM4RNDS32_MEM_RAX(0)
	VPSHUFB ·bswap_mask(SB), B0, B0
	VPXOR TW, B0, B0
	VMOVDQU B0, (16*0)(R8)

avxXtsSm4EncDone:
	VMOVDQU TW, (16*0)(BX)
	RET

// func decryptSm4NiXts(xk *uint32, tweak *[BlockSize]byte, dst, src []byte, isGB bool)
TEXT ·decryptSm4NiXts(SB),0,$256-65
	MOVQ xk+0(FP), AX
	MOVQ tweak+8(FP), BX
	MOVQ dst+16(FP), CX
	MOVQ src+40(FP), DX
	MOVQ src_len+48(FP), DI
	MOVBQZX isGB+64(FP), R12

	TESTQ R12, R12
	JNE avx2_gb_init
	VMOVDQU gcmPoly<>(SB), POLY
	JMP avx2_init_done
avx2_gb_init:
	VMOVDQU gbGcmPoly<>(SB), POLY
avx2_init_done:	
	VMOVDQU (0*16)(BX), TW

avxXtsSm4DecOctets:
	CMPQ DI, $128
	JB avxXtsSm4DecNibbles
	SUBQ $128, DI

	TESTQ R12, R12
	JNE avx2_gb_8tweaks
	// prepare tweaks
	avxPrepare8Tweaks
	JMP avx2_8tweaks_done
avx2_gb_8tweaks:
	avxPrepareGB8Tweaks
avx2_8tweaks_done:
	// load 8 blocks for decryption
	avxLoad8Blocks

	VPSHUFB ·flip_mask(SB), B0, B0
	VPSHUFB ·flip_mask(SB), B1, B1
	VPSHUFB ·flip_mask(SB), B2, B2
	VPSHUFB ·flip_mask(SB), B3, B3
	VPSHUFB ·flip_mask(SB), B4, B4
	VPSHUFB ·flip_mask(SB), B5, B5
	VPSHUFB ·flip_mask(SB), B6, B6
	VPSHUFB ·flip_mask(SB), B7, B7
	VSM4RNDS32_MEM_RAX(0)
	VSM4RNDS32_MEM_RAX(1)
	VSM4RNDS32_MEM_RAX(2)
	VSM4RNDS32_MEM_RAX(3)
	VSM4RNDS32_MEM_RAX(4)
	VSM4RNDS32_MEM_RAX(5)
	VSM4RNDS32_MEM_RAX(6)
	VSM4RNDS32_MEM_RAX(7)
	VPSHUFB ·bswap_mask(SB), B0, B0
	VPSHUFB ·bswap_mask(SB), B1, B1
	VPSHUFB ·bswap_mask(SB), B2, B2
	VPSHUFB ·bswap_mask(SB), B3, B3
	VPSHUFB ·bswap_mask(SB), B4, B4
	VPSHUFB ·bswap_mask(SB), B5, B5
	VPSHUFB ·bswap_mask(SB), B6, B6
	VPSHUFB ·bswap_mask(SB), B7, B7

	avxStore8Blocks

	LEAQ 128(DX), DX
	LEAQ 128(CX), CX

	JMP avxXtsSm4DecOctets

avxXtsSm4DecNibbles:
	CMPQ DI, $64
	JB avxXtsSm4DecSingles
	SUBQ $64, DI

	// prepare tweaks
	TESTQ R12, R12
	JNE avx2_gb_4tweaks
	avxPrepare4Tweaks
	JMP avx2_4tweaks_done
avx2_gb_4tweaks:
	avxPrepareGB4Tweaks
avx2_4tweaks_done:
	// load 4 blocks for decryption
	avxLoad4Blocks

	VPSHUFB ·flip_mask(SB), B0, B0
	VPSHUFB ·flip_mask(SB), B1, B1
	VPSHUFB ·flip_mask(SB), B2, B2
	VPSHUFB ·flip_mask(SB), B3, B3
	VSM4RNDS32_MEM_RAX(0)
	VSM4RNDS32_MEM_RAX(1)
	VSM4RNDS32_MEM_RAX(2)
	VSM4RNDS32_MEM_RAX(3)
	VPSHUFB ·bswap_mask(SB), B0, B0
	VPSHUFB ·bswap_mask(SB), B1, B1
	VPSHUFB ·bswap_mask(SB), B2, B2
	VPSHUFB ·bswap_mask(SB), B3, B3

	avxStore4Blocks

	LEAQ 64(DX), DX
	LEAQ 64(CX), CX

avxXtsSm4DecSingles:
	CMPQ DI, $32
	JB avxXtsSm4DecTail
	SUBQ $16, DI

	// load 1 block for decryption
	VMOVDQU (16*0)(DX), B0
	
	VPXOR TW, B0, B0
	VPSHUFB ·flip_mask(SB), B0, B0
	VSM4RNDS32_MEM_RAX(0)
	VPSHUFB ·bswap_mask(SB), B0, B0
	VPXOR TW, B0, B0
	VMOVDQU B0, (16*0)(CX)
	TESTQ R12, R12
	JNE avx2_gb_sigle_mul2
	avxMul2Inline
	JMP avx2_sigle_mul2_done
avx2_gb_sigle_mul2:
	avxMul2GBInline
avx2_sigle_mul2_done:
	LEAQ 16(DX), DX
	LEAQ 16(CX), CX

	JMP avxXtsSm4DecSingles

avxXtsSm4DecTail:
	TESTQ DI, DI
	JE avxXtsSm4DecDone

	CMPQ DI, $16
	JE avxXtsSm4DecLastBlock

	// length > 16
	// load 1 block for decryption
	VMOVDQU (16*0)(DX), B0
	VMOVDQU TW, B5
	TESTQ R12, R12
	JNE avx2_gb_tail_mul2
	avxMul2Inline
	JMP avx2_tail_mul2_done
avx2_gb_tail_mul2:
	avxMul2GBInline
avx2_tail_mul2_done:
	VPXOR TW, B0, B0
	VPSHUFB ·flip_mask(SB), B0, B0
	VSM4RNDS32_MEM_RAX(0)
	VPSHUFB ·bswap_mask(SB), B0, B0
	VPXOR TW, B0, B0
	VMOVDQU B0, (16*0)(CX)
	VMOVDQU B5, TW

	SUBQ $16, DI
	LEAQ 16(DX), DX
	LEAQ 16(CX), CX
	LEAQ -16(CX), R8
	VMOVDQU B0, (16*0)(SP)

	CMPQ DI, $8
	JB   avx_loop_1b
	SUBQ  $8, DI
	MOVQ (DX)(DI*1), R9
	MOVQ (SP)(DI*1), R10
	MOVQ R9, (SP)(DI*1)
	MOVQ R10, (CX)(DI*1)

	TESTQ DI, DI
	JE avxXtsSm4DecTailDec

avx_loop_1b:
	SUBQ  $1, DI
	MOVB (DX)(DI*1), R9
	MOVB (SP)(DI*1), R10
	MOVB R9, (SP)(DI*1)
	MOVB R10, (CX)(DI*1)
	TESTQ DI, DI
	JNE   avx_loop_1b

avxXtsSm4DecTailDec:
	VMOVDQU (16*0)(SP), B0
	VPXOR TW, B0, B0
	VPSHUFB ·flip_mask(SB), B0, B0
	VSM4RNDS32_MEM_RAX(0)
	VPSHUFB ·bswap_mask(SB), B0, B0
	VPXOR TW, B0, B0
	VMOVDQU B0, (16*0)(R8)
	JMP avxXtsSm4DecDone

avxXtsSm4DecLastBlock:
	VMOVDQU (16*0)(DX), B0
	VPXOR TW, B0, B0
	VPSHUFB ·flip_mask(SB), B0, B0
	VSM4RNDS32_MEM_RAX(0)
	VPSHUFB ·bswap_mask(SB), B0, B0
	VPXOR TW, B0, B0
	VMOVDQU B0, (16*0)(CX)
	TESTQ R12, R12
	JNE avx2_gb_last_mul2
	avxMul2Inline
	JMP avxXtsSm4DecDone
avx2_gb_last_mul2:
	avxMul2GBInline

avxXtsSm4DecDone:
	VMOVDQU TW, (16*0)(BX)
	RET
