// Copyright 2025 Sun Yimin. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.
// Code generated by generate.go. DO NOT EDIT.

package mldsa

import (
	"crypto"
	"crypto/sha3"
	"crypto/subtle"
	"encoding/asn1"
	"errors"
	"io"
	"sync"
	"unsafe"
)

var _ crypto.Signer = (*PrivateKey65)(nil)
var _ crypto.Signer = (*Key65)(nil)

// A PrivateKey65 is the private key for the ML-DSA-65 signature scheme.
type PrivateKey65 struct {
	rho        [32]byte         // public random seed
	k          [32]byte         // private random seed for signing
	tr         [64]byte         // pre-cached public key Hash, H(pk, 64)
	s1         [l65]ringElement // private secret of size L with short coefficients (-4..4) or (-2..2)
	s2         [k65]ringElement // private secret of size K with short coefficients (-4..4) or (-2..2)
	t0         [k65]ringElement // the Polynomial encoding of the 13 LSB of each coefficient of the uncompressed public key polynomial t. This is saved as part of the private key.
	t1         [k65]ringElement // the Polynomial encoding of the 10 MSB of each coefficient of the uncompressed public key polynomial t. This is saved as part of the public key.
	s1NTTCache [l65]nttElement
	s2NTTCache [k65]nttElement
	t0NTTCache [k65]nttElement
	a          [k65 * l65]nttElement // a is generated and stored in NTT representation
	nttOnce    sync.Once
	t1Once     sync.Once
}

// Public returns the public key corresponding to the private key.
// Although we can derive the public key from the private key,
// but we do NOT need to derive it at most of the time.
func (sk *PrivateKey65) Public() crypto.PublicKey {
	sk.ensureT1()
	return &PublicKey65{
		rho: sk.rho,
		t1:  sk.t1,
		tr:  sk.tr,
		a:   sk.a,
	}
}

func (sk *PrivateKey65) ensureNTT() {
	sk.nttOnce.Do(func() {
		for i := range sk.s1NTTCache {
			nttAssign(&sk.s1NTTCache[i], &sk.s1[i])
		}
		for i := range sk.s2NTTCache {
			nttAssign(&sk.s2NTTCache[i], &sk.s2[i])
		}
		for i := range sk.t0NTTCache {
			nttAssign(&sk.t0NTTCache[i], &sk.t0[i])
		}
	})
}

func (sk *PrivateKey65) ensureT1() {
	sk.ensureNTT()
	sk.t1Once.Do(func() {
		// t = NTT_inv(A' * NTT(s1)) + s2
		s1NTT := &sk.s1NTTCache
		A := &sk.a
		var nttT [k65]nttElement

		for i := range nttT {
			nttMatRowVecMul(&nttT[i], &s1NTT[0], &A[i*l65], l65)
		}
		var t [k65]ringElement
		t1 := &sk.t1
		for i := range nttT {
			inverseNTTAssign(&t[i], &nttT[i])
			polyAddAssign(&t[i], &sk.s2[i])
			// compress t
			for j := range n {
				t1[i][j], _ = power2Round(t[i][j])
			}
		}
	})
}

// A Key65 is the key pair for the ML-DSA-65 signature scheme.
type Key65 struct {
	PrivateKey65
	xi [32]byte // input seed
}

// A PublicKey65 is the public key for the ML-DSA-65 signature scheme.
type PublicKey65 struct {
	rho       [32]byte
	t1        [k65]ringElement
	tr        [64]byte // H(pk, 64), need to further check if public key requires it
	tNTTCache [k65]nttElement
	a         [k65 * l65]nttElement // a is generated and stored in NTT representation
	nttOnce   sync.Once
}

// Public generates and returns the corresponding public key for the given
// Key65 instance.
func (sk *Key65) Public() crypto.PublicKey {
	return &PublicKey65{
		rho: sk.rho,
		t1:  sk.t1,
		tr:  sk.tr,
		a:   sk.a,
	}
}

// Seed returns a byte slice of the secret key's seed value.
func (sk *Key65) Seed() []byte {
	var b [SeedSize]byte
	copy(b[:], sk.xi[:])
	return b[:]
}

func (pk *PublicKey65) Equal(x crypto.PublicKey) bool {
	xx, ok := x.(*PublicKey65)
	if !ok {
		return false
	}
	eq := subtle.ConstantTimeCompare(pk.rho[:], xx.rho[:]) &
		constantTimeEqualRingElementArray(pk.t1[:], xx.t1[:])
	return eq == 1
}

// Bytes converts the PublicKey65 instance into a byte slice.
// See FIPS 204, Algorithm 22, pkEncode()
func (pk *PublicKey65) Bytes() []byte {
	// The actual logic is in a separate function to outline this allocation.
	b := make([]byte, 0, PublicKeySize65)
	return pk.bytes(b)
}

func (pk *PublicKey65) bytes(b []byte) []byte {
	b = append(b, pk.rho[:]...)
	for _, f := range pk.t1 {
		b = simpleBitPack10Bits(b, f)
	}
	return b
}

func (pk *PublicKey65) ensureNTT() {
	pk.nttOnce.Do(func() {
		for i := range k65 {
			for j := range n {
				pk.tNTTCache[i][j] = pk.t1[i][j] << d
			}
			internalNTT((*ringElement)(&pk.tNTTCache[i]))
		}
	})
}

// Bytes converts the PrivateKey65 instance into a byte slice.
// See FIPS 204, Algorithm 24, skEncode()
func (sk *PrivateKey65) Bytes() []byte {
	b := make([]byte, 0, PrivateKeySize65)
	return sk.bytes(b)
}

func (sk *PrivateKey65) bytes(b []byte) []byte {
	b = append(b, sk.rho[:]...)
	b = append(b, sk.k[:]...)
	b = append(b, sk.tr[:]...)
	for _, f := range sk.s1 {
		b = bitPackSigned4(b, f)
	}
	for _, f := range sk.s2 {
		b = bitPackSigned4(b, f)
	}
	for _, f := range sk.t0 {
		b = bitPackSigned4096(b, f)
	}
	return b
}

func (sk *PrivateKey65) Equal(x any) bool {
	xx, ok := x.(*PrivateKey65)
	if !ok {
		return false
	}
	eq := subtle.ConstantTimeCompare(sk.rho[:], xx.rho[:]) &
		subtle.ConstantTimeCompare(sk.k[:], xx.k[:]) &
		subtle.ConstantTimeCompare(sk.tr[:], xx.tr[:]) &
		constantTimeEqualRingElementArray(sk.s1[:], xx.s1[:]) &
		constantTimeEqualRingElementArray(sk.s2[:], xx.s2[:]) &
		constantTimeEqualRingElementArray(sk.t0[:], xx.t0[:])
	return eq == 1
}

// GenerateKey65 generates a new Key65 (ML-DSA-65) using the provided random source.
func GenerateKey65(rand io.Reader) (*Key65, error) {
	// The actual logic is in a separate function to outline this allocation.
	sk := &Key65{}
	return generateKey65(sk, rand)
}

func generateKey65(sk *Key65, rand io.Reader) (*Key65, error) {
	// Generate a random seed.
	var seed [SeedSize]byte
	if _, err := io.ReadFull(rand, seed[:]); err != nil {
		return nil, err
	}
	dsaKeyGen65(sk, &seed)
	return sk, nil
}

// NewKey65 creates a new instance of Key65 using the provided seed.
func NewKey65(seed []byte) (*Key65, error) {
	// The actual logic is in a separate function to outline this allocation.
	sk := &Key65{}
	return newPrivateKey65FromSeed(sk, seed)
}

func newPrivateKey65FromSeed(sk *Key65, seed []byte) (*Key65, error) {
	if len(seed) != SeedSize {
		return nil, errors.New("mldsa: invalid seed length")
	}
	xi := (*[32]byte)(seed)
	dsaKeyGen65(sk, xi)
	return sk, nil
}

func dsaKeyGen65(sk *Key65, xi *[32]byte) {
	sk.xi = *xi
	H := sha3.NewSHAKE256()
	H.Write(xi[:])
	H.Write([]byte{k65, l65})
	var K [128]byte
	H.Read(K[:])
	rho, rho1 := K[:32], K[32:96]
	k := K[96:]

	sk.rho = [32]byte(rho)
	sk.k = [32]byte(k)

	s1 := &sk.s1
	s2 := &sk.s2
	// Algorithm 33, ExpandS
	for s := range byte(l65) {
		s1[s] = rejBoundedPoly(H, rho1, eta4, 0, s)
	}
	for r := range byte(k65) {
		s2[r] = rejBoundedPoly(H, rho1, eta4, 0, r+l65)
	}

	// Using rho generate A' = A in NTT form
	A := &sk.a
	// Algorithm 32, ExpandA — batch 4 elements at a time using rejNTTPolyx4
	{
		total := k65 * l65
		idx := 0
		for ; idx+4 <= total; idx += 4 {
			var indices [4][2]byte
			for b := range 4 {
				elem := idx + b
				indices[b] = [2]byte{byte(elem % l65), byte(elem / l65)}
			}
			res := rejNTTPolyx4(rho, indices)
			A[idx], A[idx+1], A[idx+2], A[idx+3] = res[0], res[1], res[2], res[3]
		}
		if idx < total {
			G128 := sha3.NewSHAKE128()
			for ; idx < total; idx++ {
				A[idx] = rejNTTPoly(G128, rho, byte(idx%l65), byte(idx/l65))
			}
		}
	}

	// t = NTT_inv(A' * NTT(s1)) + s2
	var s1NTT [l65]nttElement
	var nttT [k65]nttElement
	for i := range s1 {
		nttAssign(&s1NTT[i], &s1[i])
	}
	for i := range nttT {
		nttMatRowVecMul(&nttT[i], &s1NTT[0], &A[i*l65], l65)
	}
	var t [k65]ringElement
	t0 := &sk.t0
	t1 := &sk.t1
	for i := range nttT {
		inverseNTTAssign(&t[i], &nttT[i])
		polyAddAssign(&t[i], &s2[i])
		// compress t
		for j := range n {
			t1[i][j], t0[i][j] = power2Round(t[i][j])
		}
	}
	H.Reset()
	H.Write(sk.rho[:])
	var ekBuf [encodingSize10]byte
	for _, f := range sk.t1 {
		packed := simpleBitPack10Bits(ekBuf[:0], f)
		H.Write(packed)
	}
	H.Read(sk.tr[:])
}

// NewPublicKey65 decode an public key from its encoded form.
// See FIPS 204, Algorithm 23 pkDecode()
func NewPublicKey65(b []byte) (*PublicKey65, error) {
	// The actual logic is in a separate function to outline this allocation.
	pk := &PublicKey65{}
	return parsePublicKey65(pk, b)
}

// See FIPS 204, Algorithm 23 pkDecode()
func parsePublicKey65(pk *PublicKey65, b []byte) (*PublicKey65, error) {
	if len(b) != PublicKeySize65 {
		return nil, errors.New("mldsa: invalid public key length")
	}

	H := sha3.NewSHAKE256()
	H.Write(b)
	H.Read(pk.tr[:])

	copy(pk.rho[:], b[:32])
	b = b[32:]
	for i := range k65 {
		simpleBitUnpack10Bits(b, &pk.t1[i])
		b = b[encodingSize10:]
	}

	A := &pk.a
	rho := pk.rho[:]
	// Algorithm 32, ExpandA — batch 4 elements at a time using rejNTTPolyx4
	{
		total := k65 * l65
		idx := 0
		for ; idx+4 <= total; idx += 4 {
			var indices [4][2]byte
			for b := range 4 {
				elem := idx + b
				indices[b] = [2]byte{byte(elem % l65), byte(elem / l65)}
			}
			res := rejNTTPolyx4(rho, indices)
			A[idx], A[idx+1], A[idx+2], A[idx+3] = res[0], res[1], res[2], res[3]
		}
		if idx < total {
			G128 := sha3.NewSHAKE128()
			for ; idx < total; idx++ {
				A[idx] = rejNTTPoly(G128, rho, byte(idx%l65), byte(idx/l65))
			}
		}
	}
	return pk, nil
}

// NewPrivateKey65 decode an private key from its encoded form.
// See FIPS 204, Algorithm 25 skDecode()
func NewPrivateKey65(b []byte) (*PrivateKey65, error) {
	// The actual logic is in a separate function to outline this allocation.
	sk := &PrivateKey65{}
	return parsePrivateKey65(sk, b)
}

// See FIPS 204, Algorithm 25 skDecode()
// Decode a private key from its encoded form.
func parsePrivateKey65(sk *PrivateKey65, b []byte) (*PrivateKey65, error) {
	if len(b) != PrivateKeySize65 {
		return nil, errors.New("mldsa: invalid private key length")
	}
	copy(sk.rho[:], b[:32])
	copy(sk.k[:], b[32:64])
	copy(sk.tr[:], b[64:128])
	b = b[128:]
	for i := range l65 {
		f, err := bitUnpackSigned4(b)
		if err != nil {
			return nil, err
		}
		sk.s1[i] = f
		b = b[encodingSize4:]
	}
	for i := range k65 {
		f, err := bitUnpackSigned4(b)
		if err != nil {
			return nil, err
		}
		sk.s2[i] = f
		b = b[encodingSize4:]
	}
	for i := range k65 {
		bitUnpackSigned4096(b, &sk.t0[i])
		b = b[encodingSize13:]
	}
	A := &sk.a
	rho := sk.rho[:]
	// Algorithm 32, ExpandA — batch 4 elements at a time using rejNTTPolyx4
	{
		total := k65 * l65
		idx := 0
		for ; idx+4 <= total; idx += 4 {
			var indices [4][2]byte
			for b := range 4 {
				elem := idx + b
				indices[b] = [2]byte{byte(elem % l65), byte(elem / l65)}
			}
			res := rejNTTPolyx4(rho, indices)
			A[idx], A[idx+1], A[idx+2], A[idx+3] = res[0], res[1], res[2], res[3]
		}
		if idx < total {
			G128 := sha3.NewSHAKE128()
			for ; idx < total; idx++ {
				A[idx] = rejNTTPoly(G128, rho, byte(idx%l65), byte(idx/l65))
			}
		}
	}
	return sk, nil
}

// Sign signs the provided digest using the private key. It is a wrapper around SignMessage.
// It satisfies the crypto.Signer interface.
func (sk *PrivateKey65) Sign(rand io.Reader, digest []byte, opts crypto.SignerOpts) ([]byte, error) {
	return sk.SignMessage(rand, digest, opts)
}

// SignMessage signs a message with the private key.
// It satisfies the crypto.MessageSigner interface.
//
// The function supports pre-hashing the message by providing a hash OID in the options.
// Context data can also be provided, but is limited to 255 bytes.
func (sk *PrivateKey65) SignMessage(rand io.Reader, message []byte, opts crypto.SignerOpts) ([]byte, error) {
	var (
		context   []byte
		hashOID   asn1.ObjectIdentifier
		indicator byte = 0
	)
	if opts, ok := opts.(*Options); ok {
		context = opts.Context
		hashOID = opts.PrehashOID
	}
	if len(hashOID) != 0 {
		var err error
		if message, err = preHash(hashOID, message); err != nil {
			return nil, err
		}
		indicator = 1
	}
	if len(message) == 0 {
		return nil, errors.New("mldsa: empty message")
	}
	if len(context) > 255 {
		return nil, errors.New("mldsa: context too long")
	}
	var seed [SeedSize]byte
	if _, err := io.ReadFull(rand, seed[:]); err != nil {
		return nil, err
	}
	H := sha3.NewSHAKE256()
	H.Write(sk.tr[:])
	H.Write([]byte{indicator, byte(len(context))})
	if len(context) > 0 {
		H.Write(context)
	}
	H.Write(message)
	var mu [64]byte
	H.Read(mu[:])

	return sk.signInternal(seed[:], mu[:])
}

// See FIPS 204, Algorithm 7 ML-DSA.Sign_internal()
func (sk *PrivateKey65) signInternal(seed, mu []byte) ([]byte, error) {
	var rho2 [64 + 2]byte
	H := sha3.NewSHAKE256()
	H.Write(sk.k[:])
	H.Write(seed[:])
	H.Write(mu[:])
	H.Read(rho2[:64])
	A := &sk.a

	sk.ensureNTT()
	zNormThreshold := int(gamma1TwoPower19 - beta65)
	r0NormThreshold := int(gamma2QMinus1Div32 - beta65)

	// rejection sampling loop
	for kappa := 0; ; kappa += l65 {
		// expand mask and compute y in NTT form
		var (
			y    [l65]ringElement
			yNTT [l65]nttElement
		)
		for i := range l65 {
			index := kappa + i
			rho2[64] = byte(index)
			rho2[65] = byte(index >> 8)
			expandMaskInto(&y[i], rho2[:], gamma1TwoPower19)
			nttAssign(&yNTT[i], &y[i])
		}
		// compute w and absorb packed HighBits(w) into the commitment hash input
		var (
			cTilde    [lambda192 / 4]byte
			w1Encoded [encodingSize4]byte
			wNTT      [k65]nttElement
		)
		w := unsafe.Slice((*ringElement)(unsafe.Pointer(&wNTT[0])), k65)
		H.Reset()
		H.Write(mu[:])
		for i := range k65 {
			nttMatRowVecMul(&wNTT[i], &yNTT[0], &A[i*l65], l65)
			internalInverseNTT(&wNTT[i])
			simpleBitPack4BitsHighBits(w1Encoded[:], &w[i], gamma2QMinus1Div32)
			H.Write(w1Encoded[:])
		}
		// commitment hash
		H.Read(cTilde[:])
		// verifier's challenge
		var c ringElement
		sampleInBallInto(&c, cTilde[:], tau49)
		var cNTT nttElement
		nttAssign(&cNTT, &c)

		var (
			z  [l65]ringElement
			r0 [k65][n]int32
		)
		// compute z = <<cs1>> + y
		for i := range l65 {
			nttMul((*nttElement)(&z[i]), &cNTT, &sk.s1NTTCache[i])
			internalInverseNTT((*nttElement)(&z[i]))
			polyAddAssign(&z[i], &y[i])
		}
		zNorm := vectorInfinityNorm(z[:], 0)

		// if zNorm >= gamma1 - beta, then continue
		if subtle.ConstantTimeLessOrEq(zNormThreshold, zNorm) == 1 {
			continue
		}

		var (
			ct0 [k65]ringElement
			cs2 [k65]ringElement
		)
		r0Norm := 0
		// compute cs2 and r0 = LowBits(w - <<cs2>>)
		for i := range k65 {
			nttMul((*nttElement)(&cs2[i]), &cNTT, &sk.s2NTTCache[i])
			internalInverseNTT((*nttElement)(&cs2[i]))
			decomposeSubToR0(&r0[i], &w[i], &cs2[i], gamma2QMinus1Div32)
			r0Norm = polyInfinityNormSigned(&r0[i], r0Norm)
		}

		// if r0Norm >= gamma2 - beta, then continue
		if subtle.ConstantTimeLessOrEq(r0NormThreshold, r0Norm) == 1 {
			continue
		}

		ct0Norm := 0
		for i := range k65 {
			nttMul((*nttElement)(&ct0[i]), &cNTT, &sk.t0NTTCache[i])
			internalInverseNTT((*nttElement)(&ct0[i]))
			ct0Norm = polyInfinityNorm(&ct0[i], ct0Norm)
		}

		// if ct0Norm >= gamma2, then continue
		if subtle.ConstantTimeLessOrEq(gamma2QMinus1Div32, ct0Norm) == 1 {
			continue
		}
		// make hint
		var hints [k65]ringElement
		vectorMakeHint(ct0[:], cs2[:], w[:], hints[:], gamma2QMinus1Div32)
		// if the number of 1 in the hint is greater than omega, then continue
		if subtle.ConstantTimeLessOrEq(int(omega55+1), vectorCountOnes(hints[:])) == 1 {
			continue
		}
		// signature encoding
		sig := make([]byte, 0, sigEncodedLen65)
		sig = append(sig, cTilde[:]...)
		for i := range l65 {
			sig = bitPackSignedTwoPower19(sig, &z[i])
		}
		return hintBitPack(sig, hints[:], omega55), nil
	}
}

// VerifyWithOptions verifies a signature against a message using the public key with additional options.
func (pk *PublicKey65) VerifyWithOptions(sig []byte, message []byte, opts crypto.SignerOpts) bool {
	var (
		context   []byte
		hashOID   asn1.ObjectIdentifier
		indicator byte = 0
	)
	if opts, ok := opts.(*Options); ok {
		context = opts.Context
		hashOID = opts.PrehashOID
	}
	if len(hashOID) != 0 {
		var err error
		if message, err = preHash(hashOID, message); err != nil {
			return false
		}
		indicator = 1
	}

	if len(message) == 0 {
		return false
	}
	if len(context) > 255 {
		return false
	}
	if len(sig) != sigEncodedLen65 {
		return false
	}
	H := sha3.NewSHAKE256()
	H.Write(pk.tr[:])
	H.Write([]byte{indicator, byte(len(context))})
	if len(context) > 0 {
		H.Write(context)
	}
	H.Write(message)
	var mu [64]byte
	H.Read(mu[:])

	return pk.verifyInternal(sig, mu[:])
}

// See FIPS 204, Algorithm 8 ML-DSA.Verify_internal()
func (pk *PublicKey65) verifyInternal(sig, mu []byte) bool {
	// Decode the signature
	cTilde := sig[:lambda192/4]
	sig = sig[lambda192/4:]

	var zNTT [l65]nttElement
	zNorm := 0
	for i := range l65 {
		zPoly := (*ringElement)(&zNTT[i])
		bitUnpackSignedTwoPower19(sig, zPoly)
		zNorm = polyInfinityNorm(zPoly, zNorm)
		internalNTT(zPoly)
		sig = sig[encodingSize20:]
	}
	// Early check: if zNorm >= gamma1 - beta, reject
	if subtle.ConstantTimeLessOrEq(int(gamma1TwoPower19-beta65), zNorm) == 1 {
		return false
	}

	var hints [k65]ringElement
	if !hintBitUnpack(sig, hints[:], omega55) {
		return false
	}
	// verifier's challenge
	var c ringElement
	sampleInBallInto(&c, cTilde[:], tau49)
	var cNTT nttElement
	nttAssign(&cNTT, &c)

	pk.ensureNTT()
	H := sha3.NewSHAKE256()
	H.Write(mu[:])
	var (
		w1        ringElement
		w1Encoded [encodingSize4]byte
	)
	for i := range k65 {
		var wApprox nttElement
		nttMatRowVecMul(&wApprox, &zNTT[0], &pk.a[i*l65], l65)
		var product nttElement
		nttMul(&product, &pk.tNTTCache[i], &cNTT)
		polySubAssign((*ringElement)(&wApprox), (*ringElement)(&product))
		internalInverseNTT(&wApprox)
		useHintPoly(&w1, &hints[i], (*ringElement)(&wApprox), gamma2QMinus1Div32)
		H.Write(simpleBitPack4Bits(w1Encoded[:0], &w1))
	}
	var cTilde1 [lambda192 / 4]byte
	H.Read(cTilde1[:])
	return subtle.ConstantTimeCompare(cTilde, cTilde1[:]) == 1
}
