// Copyright 2026 Sun Yimin. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.

//go:build (amd64 || arm64 || ppc64 || ppc64le || (riscv64 && go1.27)) && !purego

package zuc

import (
	"bytes"
	"encoding/hex"
	"os"
	"strings"
	"testing"

	"github.com/emmansun/gmsm/internal/cpuid"
	"github.com/emmansun/gmsm/internal/cryptotest/diff"
	"github.com/emmansun/gmsm/internal/deps/cpu"
)

// diffEEARefFor wraps a run so that the EEA keystream is generated by the
// pure-Go path, which is the trusted differential oracle. Forcing the
// generic fallback is always safe regardless of host features (unlike
// forcing an accelerated kernel), so the reference is also used by the fuzz
// bodies; the override is restored via t.Cleanup after every execution.
func diffEEARefFor(run diff.Run[[]byte]) diff.Run[[]byte] {
	return func(t testing.TB, c diff.Case, b *diff.Buffers) []byte {
		diff.WithValue(t, &supportsAES, false)
		return run(t, c, b)
	}
}

// diffEEAImpls returns the accelerated EEA implementation. It runs through
// the natural public dispatch (no global override), so it is safe for fuzz
// bodies, and Available consults the real dispatch state.
func diffEEAImpls(run diff.Run[[]byte]) []diff.Implementation[[]byte] {
	return []diff.Implementation[[]byte]{{
		Name:      "asm-keystream",
		Run:       run,
		Available: func() bool { return supportsAES },
		Primary:   true,
	}}
}

// diffEIARefFor wraps a run so that the MAC takes the pure-Go path: the
// keyword generation dispatches on supportsAES and the block rounds on
// supportsGFMUL, so both must be forced to the generic implementations.
func diffEIARefFor(run diff.Run[[]byte]) diff.Run[[]byte] {
	return func(t testing.TB, c diff.Case, b *diff.Buffers) []byte {
		diff.WithValue(t, &supportsAES, false)
		diff.WithValue(t, &supportsGFMUL, false)
		return run(t, c, b)
	}
}

// diffEIAImpls returns the accelerated MAC implementation through the
// natural public dispatch.
func diffEIAImpls(run diff.Run[[]byte]) []diff.Implementation[[]byte] {
	return []diff.Implementation[[]byte]{{
		Name:      "asm-mac",
		Run:       run,
		Available: func() bool { return supportsGFMUL },
		Primary:   true,
	}}
}

// checkDispatch asserts that the dispatch variables are consistent with the
// CPU features of the host.
func checkDispatch(t *testing.T) {
	wantAES := cpuid.HasAES || (cpu.RISCV64.HasZvkned && cpu.RISCV64.HasZbb)
	if supportsAES != wantAES {
		t.Errorf("supportsAES = %v, want %v", supportsAES, wantAES)
	}
	wantGFMUL := cpuid.HasGFMUL || cpuid.HasVPMSUMD || cpu.RISCV64.HasZvbc
	if supportsGFMUL != wantGFMUL {
		t.Errorf("supportsGFMUL = %v, want %v", supportsGFMUL, wantGFMUL)
	}
}

// TestDiffReferenceKAT anchors the forced pure-Go paths — the differential
// oracles — to the specification KATs before they are used as references.
// On the pure-Go build this is covered by the public-path anchor tests
// instead, because the generic path is the public path there.
func TestDiffReferenceKAT(t *testing.T) {
	tv := katEEAVectors[0]
	key, err := hex.DecodeString(tv.key)
	if err != nil {
		t.Fatal(err)
	}
	in, err := hex.DecodeString(tv.in)
	if err != nil {
		t.Fatal(err)
	}
	want, err := hex.DecodeString(tv.out)
	if err != nil {
		t.Fatal(err)
	}
	diff.WithValue(t, &supportsAES, false)
	c, err := NewEEACipher(key, tv.count, tv.bearer, tv.direction)
	if err != nil {
		t.Fatal(err)
	}
	out := make([]byte, len(in))
	copy(out, in)
	c.XORKeyStream(out, out)
	if !bytes.Equal(out, want) {
		t.Fatalf("generic EEA reference does not reproduce the KAT: got %x", out)
	}

	kat := katEIAVectors[0]
	diff.WithValue(t, &supportsGFMUL, false)
	h, err := NewEIAHash(kat.key, kat.count, kat.bearer, kat.direction)
	if err != nil {
		t.Fatal(err)
	}
	mac := h.Finish(kat.in, kat.nbits)
	wantMac, err := hex.DecodeString(kat.mac)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(mac, wantMac) {
		t.Fatalf("generic EIA reference does not reproduce the KAT: got %x", mac)
	}
}

// TestDiffRequiredKernels enforces kernel availability on CI runners that
// guarantee the CPU features (native hardware, Intel SDE, QEMU with the
// extension enabled). DIFF_REQUIRE holds a comma-separated list of kernel
// classes; the list may be shared across packages, and each package
// validates only the classes it owns (unknown names are ignored).
func TestDiffRequiredKernels(t *testing.T) {
	req := os.Getenv("DIFF_REQUIRE")
	if req == "" {
		t.Skip("DIFF_REQUIRE not set")
	}
	for _, name := range strings.Split(req, ",") {
		switch name {
		case "zuc-eea":
			if !supportsAES {
				t.Errorf("kernel %q required but supportsAES is false", name)
			}
		case "zuc-eia":
			if !supportsGFMUL {
				t.Errorf("kernel %q required but supportsGFMUL is false", name)
			}
		}
	}
}
