# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: arm64-qemu

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

permissions:
  contents: read

jobs:

  test:
    strategy:
      matrix:
        go-version: [1.24.x]
        arch: [arm64]  
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
      with:
        egress-policy: audit

    - name: Set up Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        go-version: ${{ matrix.go-version }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

    - name: Check out code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      
    - name: Test
      run: go test -v -short ./sm3/...
      env:
        DISABLE_SM3NI: 1
        DISABLE_SM4NI: 1
        GODEBUG: x509sha1=1
        GOARCH: ${{ matrix.arch }}      

    - name: Test Force SM4 Single Block with AES-NI
      run: go test -v -short ./sm4/...      
      env:
        DISABLE_SM4NI: 1
        FORCE_SM4BLOCK_AESNI: 1
        GOARCH: ${{ matrix.arch }}      
